apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "<%= serviceName %>.fullname" . }}
spec:
  secretName: {{ include "<%= serviceName %>.fullname" . }}-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.host }}
  dnsNames:
    - {{ .Values.ingress.host }}