version: '3.5'
services:
  localstack:
    image: 'localstack/localstack:1.2.0'
    container_name: localstack_main
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sns
      - DEBUG=1
      - DEFAULT_REGION=eu-south-2
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d/
      - /var/run/docker.sock:/var/run/docker.sock

