{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ include "<%= serviceName %>.fullname" . }}
  labels:
    {{- include "<%= serviceName %>.labels" . | nindent 4 }}
data:
  {{- with .Values.secrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}