apiVersion: v1
kind: Service
metadata:
  name: {{ include "<%= serviceName %>.fullname" . }}
  labels:
    {{- include "<%= serviceName %>.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "<%= serviceName %>.selectorLabels" . | nindent 4 }}
