name: Publish package to npm public registry

on:
  release:
    types: [ published ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out the repository
      uses: actions/checkout@v3
    - name: Setup node version 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
    - name: Build artifact
      run: cd packages/@guidesmiths/cuckoojs-cli && npm ci --production && npm run build
    - name: Publish package to npm
      run: cd packages/@guidesmiths/cuckoojs-cli && npm publish --ignore-scripts --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_GUIDESMITHS }}