name: Publish packages to npm public registry

on:
  release:
    types: [ published ]

jobs:
  check-cuckoojs-schematics:
    runs-on: ubuntu-latest
    outputs:
      version-changed: ${{ steps.version-change.outputs.version-changed }}
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v3
      - name: Check version changes
        uses: EndBug/version-check@v2
        id: version-changed
        with:
          file-name: ./packages/@guidesmiths/cuckoojs-schematics/package.json

  publish-npm-cuckoojs-schematics:
    runs-on: ubuntu-latest
    needs: check-cuckoojs-schematics
    if: ${{ needs.check-cuckoojs-schematics.outputs.version-changed }} === "true"
    steps:
    - name: Check-out the repository
      uses: actions/checkout@v3
    - name: Setup node version 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Install dependencies
      run: npm i -w @guidesmiths/cuckoojs-schematics
    - name: Build artifact
      run: npm run build -w @guidesmiths/cuckoojs-schematics
    - name: Publish package to npm
      run: npm publish --ignore-scripts --access public -w @guidesmiths/cuckoojs-schematics
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_GUIDESMITHS }}

  publish-npm-cuckoojs-cli:
    runs-on: ubuntu-latest
    needs: publish-npm-cuckoojs-schematics
    steps:
    - name: Check-out the repository
      uses: actions/checkout@v3
    - name: Setup node version 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Install dependencies
      run: npm i -w @guidesmiths/cuckoojs-cli
    - name: Build artifact
      run: npm run build -w @guidesmiths/cuckoojs-cli
    - name: Publish package to npm
      run: npm publish --ignore-scripts --access public -w @guidesmiths/cuckoojs-cli
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_GUIDESMITHS }}
