name: Generate draft release

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  test:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Lerna Version
        id: extract-lerna-version
        uses: ./.github/actions/extract-lerna-version

      - name: Release
        uses: release-drafter/release-drafter@65c5fb495d1e69aa8c08a3317bc44ff8aabe9772 # v5.24.0
        with:
          tag: "v${{ steps.extract-lerna-version.outputs.lerna-version }}"
          version: "v${{ steps.extract-lerna-version.outputs.lerna-version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
