name: Version packages

on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: 'The type of version bump to perform.'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install node, npm, and dependencies
        uses: ./.github/actions/setup-and-install

      - name: Print Environment Info
        run: npx lerna info
        shell: bash

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
        shell: bash

      - name: Bump version of packages
        run: npx lerna version ${{ inputs.version-bump }} --yes --no-push --no-git-tag-version
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Lerna Version
        id: extract-lerna-version
        uses: ./.github/actions/extract-lerna-version

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: releases/bump-version-v${{ steps.extract-lerna-version.outputs.lerna-version }}
          title: releases/bump-version-v${{ steps.extract-lerna-version.outputs.lerna-version }}
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          commit-message: "chore: bump version to v${{ steps.extract-lerna-version.outputs.lerna-version }}"
          labels: releases
          body: |
            Bump packages to v${{ steps.extract-lerna-version.outputs.lerna-version }}. A new draft release will be generated on merge.
            
            Auto-generated by [create-pull-request][1] during Version workflow.
            
            [1]: https://github.com/peter-evans/create-pull-request
            
